int factorial(int n);
// ZWRACA SILNIE Z PODANEGO n
// GDY n NIE JEST LICZBA NATURALNA ZWRACA 0
// GDY WYNIK ZA DUZY ZWRACA -1

double power(double base, int exponent);
// ZWRACA base DO POTEGI exponent

int is_prime(int n);
// ZWRACA 1 JESLI PODANA LICZBA JEST LICZBA PIERWSZA (LUB JEJ WARTOSC BEZWZGLEDNA)
// ZWRACA 0 JESLI JEST 0
// ZWRACA -1 JESLI NIE JEST ZLOZONA
